### ISSUE TITLE
Crash while setting up

### ISSUE THREAD

**Issue by corristo** [SlatherOrg/slather#141]
I'm getting the following error when I try to run `slather coverage -s <path to project>`:

```
/Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.0.0.beta.2/lib/xcodeproj/plist.rb:17:in `read_from_path': Xcodeproj::Informative
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.0.0.beta.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.0.0.beta.2/lib/xcodeproj/project.rb:102:in `open'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.0.0/lib/slather/project.rb:59:in `open'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.0.0/bin/slather:95:in `project'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.0.0/bin/slather:106:in `setup_coverage_service'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.0.0/bin/slather:45:in `execute'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.0.0/bin/slather:6:in `<top (required)>'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/bin/slather:23:in `load'
	from /Users/nkasyanov/.rbenv/versions/2.0.0-p481/bin/slather:23:in `<main>'
```

Can I provide any additional info?

**Comment by corristo** [comment]
Okay, that was because I specified full path to `.pbxproj` file, not to `.xcodeproj`.
