### ISSUE TITLE
`NoMethodError` When Generating Coverage Report

### ISSUE THREAD

**Issue by bartjacobs** [SlatherOrg/slather#166]
Even though I can successfully run the project's test suite, running `slather coverage -s path/to/project.xcodeproj` returns the following error:

```
slather coverage -s MyProject.xcodeproj/
Slathering...
/Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:515:in `products': undefined method `children' for nil:NilClass (NoMethodError)
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/lib/slather/project.rb:108:in `first_product_name'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/lib/slather/project.rb:120:in `profdata_coverage_dir'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/lib/slather/project.rb:287:in `find_binary_file'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/lib/slather/project.rb:282:in `configure_binary_file'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/lib/slather/project.rb:199:in `configure'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/bin/slather:52:in `execute'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Users/Bart/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.0.1/bin/slather:6:in `<top (required)>'
	from /Users/Bart/.rbenv/versions/2.2.4/bin/slather:23:in `load'
	from /Users/Bart/.rbenv/versions/2.2.4/bin/slather:23:in `<main>'
```

While I am somewhat familiar with **xcodeproj**, it is unclear what the issue is. I am currently running Xcode 7.2.1. The project uses CocoaPods for dependency management and the workspace includes three projects.

- slather: 2.0.1
- xcodeproj: 0.28.2

Code coverage is enabled in the active scheme and code coverage works and looks fine in Xcode. The reason for using Slather is to convert the coverage data to the Cobertura format.

**Comment by brennantaylor** [comment]
I am having the same issue.

**Comment by brennantaylor** [comment]
@bartjacobs I resolved my issue by also passing the `--scheme MyScheme` parameter to slather.

**Comment by bartjacobs** [comment]
@brennantaylor Great. That solves the issue I was having. Thank you, Brennan.
