### ISSUE TITLE
`find_binary_file': No product binary found with custom DerivedData path

### ISSUE THREAD

**Issue by carayolthomas** [SlatherOrg/slather#192]
Hi there,

I am using Slather 2.1 on a Mac Mini. When I run `slather coverage --scheme SchemeName AppName.xcodeproj`, I get the following errors : 

> Slathering...
> No product binary found in /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/AppName-amrqcsdrozxngmcidznegfpnjcde/Build/Intermediates/CodeCoverage.
> 
> 	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
> 	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
> 	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
> 
> /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:386:in `find_binary_file': No product binary found in /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/AppName-amrqcsdrozxngmcidznegfpnjcde/Build/Intermediates/CodeCoverage. (StandardError)
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:314:in `configure_binary_file'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:221:in `configure'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/command/coverage_command.rb:46:in `execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/bin/slather:15:in `<top (required)>'
> 	from /usr/local/bin/slather:23:in `load'
> 	from /usr/local/bin/slather:23:in `<main>'

Here the result of the `ls` command in `/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/AppName-amrqcsdrozxngmcidznegfpnjcde/Build/Intermediates/CodeCoverage` : 

`Coverage.profdata	Intermediates		Products		ProfileData`

I don't really understand what it is looking for. Do you have any insight about this?

Cheers,

Thomas

**Comment by ksuther** [comment]
Slather looks for a build or test product in the Products directory based on the contents of your scheme. You can try specifying `--binary-basename` to manually specify the product name if the scheme product doesn't match the output.

If you look at https://github.com/SlatherOrg/slather/blob/master/lib/slather/project.rb#L352 you can see how buildable_name is created.

**Comment by carayolthomas** [comment]
@ksuther Many thanks a lot for your help. It solves my problem. I still have an issue which is similar to https://github.com/SlatherOrg/slather/issues/103. I'll look into it and will ask more questions on the other issue if I don't succeed to solve it. 

Have a great day!

**Comment by mkujalowicz** [comment]
The latest version still has problems with detecting binaries. If I'm calling it like:
slather coverage --cobertura-xml --output-directory Build --build-directory Build --input-format profdata --scheme test --binary-basename test test.xcodeproj

it fails because it processes test.swiftmodule from Intermediates/CodeCoverage/Products/Debug-iphonesimulator instead of test.app

**Comment by alanzeino** [comment]
I think I'm having the same issue. Since our Jenkins jobs use a specific DerivedData folder, I have to pass it in using `--build-directory` for Slather to have any chance of finding the Coverage.profdata file. However when doing that, it raises the same exception.

When running locally (and not having to specify the `--build-directory` path), it works just fine, since it's using the usual DerivedData location.

**Comment by neonichu** [comment]
@alanzeino which method are you using for specifying the custom path `xcodebuild -derivedDataPath`?

**Comment by alanzeino** [comment]
Yeah we're using `-derivedDataPath` and we're setting the `CONFIGURATION_BUILD_DIR` (though I don't think that will matter). Definitely seeing the same thing that @mkujalowicz where there's both {app_name}.app and {app_name}.swiftmodule in `DerivedData/{scheme_name}-budsowgbiuirlacgutnwfpsfivgs/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/` (where app_name is the name of the compiled target and scheme_name is the name of the scheme, which happens to also be a framework).

I _think_ the issue here is that the scheme is one thing, but the .app file has a different name.

**Comment by alanzeino** [comment]
I'm going to test passing in both `--build-directory` and `--binary-file` on our CI tomorrow and see if that works. When I test it locally, it seems to still generate coverage data:

```
--build-directory /Users/alan/Library/Developer/Xcode/DerivedData/ --binary-file /Users/alan/Library/Developer/Xcode/DerivedData/{scheme_name}-budsowgbiuirlacgutnwfpsfivgs/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/{scheme_name}.framework/{scheme_name}
```

Where `{scheme_name}` is the `scheme` we're running Slather against.

**Comment by alanzeino** [comment]
Okay, so did some investigation into this one. Our specific problem is related to our use of `CONFIGURATION_BUILD_DIR`, where xcodebuild puts all the stuff you'd expect to see in `../DerivedData/{scheme_name}-asdfasdfasdf/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/` in the path specified by `CONFIGURATION_BUILD_DIR` instead.

So, by making the `--build-directory` point to our `-derivedDataPath`, and `--binary-file` point to `CONFIGURATION_BUILD_DIR/{scheme_name}.framework/{scheme_name}`, Slather works.

However, it might also be that this is _also_ due to our use of a setup like this:
```
workspace: src/Foo.xcworkspace
xcodeproj: src/Bar/Bar.xcodeproj
scheme: Foo
```

(notice that the scheme is Foo, but the xcodeproj and compiled `.app` will be `Bar.app`)

Anyway, for @mkujalowicz's issue, I [wrote a crappy script](https://gist.github.com/alanzeino/70928ea035cf97505911600cef564ced) that locally, works as expected for our case where we need to find the `{scheme_name}.framework/{scheme_name}`. This worked locally, but this was before I had my revelation about the `CONFIGURATION_BUILD_DIR`. All the script does is look at your `.slather.yml`, then tries to find the `{scheme_name}.framework/{scheme_name}` under `../DerivedData/{scheme_name}-asdfasdfasdf/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/`. Like I said, crappy script, might be making too many assumptions about how the DerivedData works, not sure.

Then, once I figured out the `CONFIGURATION_BUILD_DIR` issue, I wrote [a smaller script](https://gist.github.com/alanzeino/59ded726c0713c6ceebdde94fc8f7829) that tries to slather with `--binary-file` set to the  `CONFIGURATION_BUILD_DIR/{scheme_name}.framework/{scheme_name}` path.

So yeah, these scripts will likely only work if you're trying to Slather a framework inside your app that is named differently from your app. Hope this helps.

**Comment by yoshoten-i-sol** [comment]
Put binary_basename to product name is worked for me.

**Comment by xxi511** [comment]
In my case, my configuration is `Production Debug`.  
It works after filling in `configuration`.  

But what I don't understand is according to source code, if there is no `configuration` it should get the value from `xcscheme` ?
```
       // project.rb
    def find_binary_files
      ...
      ...
        if self.configuration
          configuration = self.configuration
        else
          configuration = xcscheme.test_action.build_configuration
        end
```

my `xcscheme`.  
```
   <TestAction
      buildConfiguration = "Production Debug"
```
