### ISSUE TITLE
Malformed coverage data?

### ISSUE THREAD

**Issue by joshrlesch** [SlatherOrg/slather#194]
Getting this error when trying to use slather when using xcode 7.3
This used to work, but after pulling in the laster master of slather into my fork, its broken now :(

```
Processing coverage file: /Users/josh.lesch/Library/Developer/Xcode/DerivedData/App-cjtrsczigiznjseugfepdeoohyvo/Build/Intermediates/CodeCoverage/Coverage.profdata
Against binary files:
    /Users/josh.lesch/Library/Developer/Xcode/DerivedData/App-cjtrsczigiznjseugfepdeoohyvo/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Pods.framework/Pods

error: Failed to load coverage: Malformed coverage data
Test Coverage: NaN%
Slathered
```

Executing with command
`slather coverage --verbose App.xcodeproj`

Have a .slather.yml file that includes

```
ignore:
  - Frameworks/*
  - Pods/*
  - ../**/*/Xcode*
  - App Unit Tests/*
  - gym_build_*

xcodeproj: App.xcodeproj
input_format: profdata
scheme: App
workspace: App.xcworkspace
```

**Comment by ksuther** [comment]
It is finding the wrong binary. It shouldn't be trying to use Pods.framework. Does the 2.1.0 release work?

**Comment by joshrlesch** [comment]
When I use the 2.1.0 release, I get the no scheme found error.

```
No shared scheme named 'App' found in /Users/josh.lesch/Documents/github/example/App.xcodeproj

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)

/Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/slather-2.1.0/lib/slather/project.rb:331:in `find_binary_file': No shared scheme named 'App' found in /Users/josh.lesch/Documents/github/example/App.xcodeproj (StandardError)
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/slather-2.1.0/lib/slather/project.rb:314:in `configure_binary_file'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/slather-2.1.0/lib/slather/project.rb:221:in `configure'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/slather-2.1.0/lib/slather/command/coverage_command.rb:46:in `execute'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/slather-2.1.0/bin/slather:15:in `<top (required)>'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/slather:23:in `load'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/slather:23:in `<main>'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by joshrlesch** [comment]
UPDATE

I finally got it working with the `--binary-basename` arg, but then I came across another problem. We use custom derivedData paths, so when I pass the path into `build-directory` slather was adding the scheme name to the end of it. So then it could find the coverage file. Here https://github.com/SlatherOrg/slather/blob/master/lib/slather/project.rb#L156

I removed the `self.scheme` from that line and it works now. Now sure if its just how my app is set up or not thought.

**Comment by ksuther** [comment]
It looks like you're hitting the path for Xcode 7.2. That should be returning nil and then falling through to line 163. Any chance you have leftover data in your custom derived data path that might be interfering?

**Comment by iwllyu** [comment]
I have the same problem. Xcode 7.3.1 and Slather 2.3.0. It's attempting to use my Pod binary instead of my app binary

**Comment by ekingo** [comment]
Finally, my method is :  change framework mach-o Type from Static Library to Dynamic Library.
