### ISSUE TITLE
slather error find_binary_files

### ISSUE THREAD

**Issue by croccio** [SlatherOrg/slather#213]
https://github.com/Backelite/sonar-swift/issues/27#issuecomment-220995086

can someone help me please?

-n Computing coverage report
-n .
/Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:445:in find_binary_files': No product binary found in /Users/antonio/Library/Developer/Xcode/DerivedData/Qui-bytbtjdboajwjvdreycwlxvvniqo/Build/Intermediates/CodeCoverage. (StandardError) from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:337:inconfigure_binary_file'
from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:240:in configure' from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/command/coverage_command.rb:48:inexecute'
from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in run' from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:inexecute'
from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in run' from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:inrun'
from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/bin/slather:15:in <top (required)>' from /usr/local/bin/slather:23:inload'
from /usr/local/bin/slather:23:in `

'
ERROR - Command 'slather coverage --input-format profdata -i .Tests. --cobertura-xml --output-directory sonar-reports --workspace Qui.xcworkspace --scheme QUI! Collaudo Esterno Qui.xcodeproj' failed with error code: 1

**Comment by neonichu** [comment]
Are there any binaries in the given path `/Users/antonio/Library/Developer/Xcode/DerivedData/Qui-bytbtjdboajwjvdreycwlxvvniqo/Build/Intermediates/CodeCoverage`?

Could be that the exclamation mark in your scheme name breaks slather right now.

**Comment by croccio** [comment]
no, there isn't

**Comment by croccio** [comment]
i've deleted exclamation mark i get same error

**Comment by croccio** [comment]
-n Computing coverage report
-n .
/Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:445:in `find_binary_files': No product binary found in /Users/antonio/Library/Developer/Xcode/DerivedData/Qui-bytbtjdboajwjvdreycwlxvvniqo/Build/Intermediates/CodeCoverage. (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:337:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:240:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/command/coverage_command.rb:48:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
ERROR - Command 'slather coverage --input-format profdata -i .*Tests.* --cobertura-xml --output-directory sonar-reports --workspace Qui.xcworkspace --scheme Qui Collaudo Esterno Qui.xcodeproj' failed with error code: 1


here you are. it's the same

**Comment by neonichu** [comment]
What's the actual name of your scheme? What's the output of `xcodebuild -list -project Collaudo Eastern Qui.xcodeproj`?

**Comment by croccio** [comment]
if i run this i get error

xcodebuild -list -project "Qui Collaudo Esterno" Qui.xcodeproj

[...]
xcodebuild: error: Unknown build action 'Qui.xcodeproj'


if i run this i get 

xcodebuild -list -project Qui.xcodeproj

[...]

Information about project "Qui":
    Targets:
        QUI
        QuiTests
        QuiUITests

    Build Configurations:
        Debug
        Collaudo Esterno
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Qui
        Qui Produzione
        Qui Collaudo Esterno

**Comment by neonichu** [comment]
Oh, I see the issue now, your scheme name contains spaces. Can you try passing `--scheme 'Qui Collaudo Esterno' ` to slather instead?

**Comment by croccio** [comment]
no, the same. i've tried to delete space from scheme name, but i get error

**Comment by croccio** [comment]
if i run slather as sudo it stuck for ever

**Comment by croccio** [comment]
i've xcode 7.3

**Comment by croccio** [comment]
@neonichu 
if i remove --scheme than it works. maybe with Xcode 7.3 the path is changed?

**Comment by vinnybad** [comment]
I'm seeing the same issue.  Were you able to resolve this @croccio ?

**Comment by sbhklr** [comment]
@croccio Spaces in schemes shouldn't be an issue. When adding a space to the test fixture's scheme the tests still pass. Make sure you run the tests before invoking slather. As @neonichu pointed out, try to locate the binary file in the project's derived data directory. Once you found it, try to run slather with 
`--binary-file "/path/to/binary"` and see what happens.

**Comment by ShuklaDevashree963** [comment]
> @croccio Spaces in schemes shouldn't be an issue. When adding a space to the test fixture's scheme the tests still pass. Make sure you run the tests before invoking slather. As @neonichu pointed out, try to locate the binary file in the project's derived data directory. Once you found it, try to run slather with
> `--binary-file "/path/to/binary"` and see what happens.

Can you explain further what this means ? I am getting the same error in Xcode 11.3

**Comment by thejeswara** [comment]
@ShuklaDevashree963 Did you found any solution for this? I am also facing same issue in Xcode 11.3.

**Comment by nurirppan** [comment]
did you found any solution brother ? i am using xcode 14.2 @croccio
