### ISSUE TITLE
Broken on new cocoapods

### ISSUE THREAD

**Issue by bootstraponline** [SlatherOrg/slather#220]
```
[16:10:14]: ▸ Error loading the plugin `slather-2.1.0`.
[16:10:14]: ▸ Gem::ConflictError - Unable to activate slather-2.1.0, because xcodeproj-1.1.0 conflicts with xcodeproj (< 1.1.0, >= 0.28.2)
[16:10:14]: ▸ /.rbenv/versions/2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
[16:10:14]: ▸ /.rbenv/versions/2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
```

we need a new gem release, I don't have permission. :( I'll have to temporarily fork the project so we can continue to use slather with fastlane.

https://github.com/instructure/slather/commit/a987885f86aa0f8148bf75db6d1da1b7552cc981

**Comment by bootstraponline** [comment]
Thanks! looks like my fork lasted only 3 minutes.

**Comment by neonichu** [comment]
💃 :)
