### ISSUE TITLE
slather code coverage error : find_binary_files

### ISSUE THREAD

**Issue by vinsp** [SlatherOrg/slather#224]
--- Step: cd .. && mkdir -p 'build/reports/unit_test' && slather coverage       --cobertura-xml       --output-directory 'build/reports/unit_test'       --input-format profdata       --build-directory DerivedData       --source-directory .       --scheme 'myAppTests'       --workspace 'myApp.xcworkspace'       --binary-basename 'myApp'       *.xcodeproj ---
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 $ cd .. && mkdir -p 'build/reports/unit_test' && slather coverage       --cobertura-xml       --output-directory 'build/reports/unit_test'       --input-format profdata       --build-directory DerivedData       --source-directory .       --scheme 'myAppTests'       --workspace 'myApp.xcworkspace'       --binary-basename 'myApp'       *.xcodeproj
 ▸ /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.2.1/lib/slather/project.rb:459:in `find_binary_files': No product binary found in DerivedData/Build/Intermediates/CodeCoverage. (StandardError)
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.2.1/lib/slather/project.rb:344:in `configure_binary_file'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.2.1/lib/slather/project.rb:240:in `configure'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.2.1/lib/slather/command/coverage_command.rb:50:in `execute'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slather-2.2.1/bin/slather:17:in `<top (required)>'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/bin/slather:23:in `load'
 ▸ from /Users/admin/.rbenv/versions/2.2.4/bin/slather:23:in `<main>'
 ▸ Slathering...
 ▸ No product binary found in DerivedData/Build/Intermediates/CodeCoverage.
 ▸ Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
 ▸ Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
 ▸ If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)

**Comment by vinsp** [comment]
After providing ```--binary-file``` argument to ```slather coverage``` command, getting following error

error: Failed to load coverage: Is a directory

**Comment by sbhklr** [comment]
@vinsp I'd avoid to specify both `--binary-basename` and `--binary-file`. Try to provide `--binary-file` with the absolute or relative path to the binary file and see if this works. E.g. `--binary-file "./build/Build/Intermediates/CodeCoverage/Products/Debug/myApp/myApp.app/myApp"`

**Comment by vinsp** [comment]
@sbhklr yeah. It's working. Should I update any project settings so that I works without hardcoding the binary file path?

**Comment by ksuther** [comment]
The `--binary-basename` parameter is meant to be used if you don't want to hardcode the binary path. It has to make a number of assumptions about where your binary is actually being built though. Use the `--verbose` parameter to have slather print out where it's looking for the binary.

Also, if you were using code coverage in Xcode 7.2 or earlier, delete your Intermediates directory to clear out any old coverage data.

**Comment by sbhklr** [comment]
@vinsp @ksuther `--binary-basename` didn't work for me either, so I switched to `--binary-file`. I'll have another look why `--binary-basename` didn't work in the first place. I'm testing a framework, maybe that's the issue.

**Comment by vinsp** [comment]
@ksuther,  ```--binary-basename``` doesn't seem to work. I have enabled ```--verbose``` flag and got following output.

slather coverage   --verbose    --cobertura-xml       --output-directory 'build/reports/unit_test'       --input-format profdata       --build-directory DerivedData       --source-directory .       --ignore '../**'       --ignore 'build/**'       --ignore 'thirdparty/**'       --ignore 'myAppTests/**'       --ignore 'myAppUITests/**'       --scheme 'myAppTests'       --workspace '../myApp.xcworkspace'   --binary-basename 'myApp' *.xcodeproj
Slathering...
No product binary found in DerivedData/Build/Intermediates/CodeCoverage.

It's searching for binary in ```DerivedData/Build/Intermediates/CodeCoverage``` folder but the binary is present in ```DerivedData/Build/Intermediates/CodeCoverage/Products/Release-iphonesimulator/RightSignature.app/RightSignature```

**Comment by ksuther** [comment]
`--binary-basename` should work with frameworks, I use it with it regularly. The most common reasons it'll fail are:

* Pre-Xcode 7.3 coverage data is in the way
* Not specifying the scheme or workspace correctly
* Not specifying the right build configuration

`find_binary_files` in project.rb is where the binary path is set. I'd suggest doing some printf debugging there if you can't get it to work.

**Comment by sbhklr** [comment]
Now I see why it doesn't work with `--binary-basename`. My project is a Pod project and the framework that I want to test is therefore built as separate product. The framework resides in a subfolder `myFramework-iOS`. Slather only looks for the binary inside `Debug-iphonesimulator`, therefore I have to specify the basename as `myFramework-iOS/myFramework.framework`in order for it to work. 
@ksuther @neonichu How about we let slather look inside subfolders as well? Something like this would work:
```
directories = Dir["#{profdata_coverage_dir}/Products/#{configuration}*/#{search_for}*"]
directories += Dir["#{profdata_coverage_dir}/Products/#{configuration}*/#{search_for}*/#{search_for}.*"]
```

**Comment by ksuther** [comment]
I don't know enough about the directory structure of CocoaPods to have much of an opinion on that. That structure looks like CocoaPods's own build magic rather than Xcode, at least from what I know.

If that's the case and it's standard for all projects using pods then I don't see any harm, I just don't know whether it's a general enough solution.

**Comment by sbhklr** [comment]
@ksuther Yes, that's what I'm thinking as well. It's not super elegant if it's just related to CocoaPods builds. However, a lot of Pod developers probably use slather, so maybe it makes sense to adjust it accordingly. @neonichu can probably clarify since he's a CP member.

**Comment by ksuther** [comment]
Another possibility would be to do something like:

```
directories += Dir["#{profdata_coverage_dir}/Products/#{configuration}*/**/#{search_for}*"]
```

That should catch all possibilities at the cost of being a bit slower. It would catch binaries embedded within other bundles though, so we'd have to do a second step where we ignore matches that are in bundles.

If putting frameworks in a <framework>-<platform> directory is normal for CocoaPods then I don't see any harm in adding a search path for it as long as it's commented as being pod-specific.

**Comment by sbhklr** [comment]
Both would work. The latter solution is probably more future proof in case CP changes something with the build directories.

**Comment by neonichu** [comment]
Right, CocoaPods 1.0 adds an additional level to `CONFIGURATION_BUILD_DIR` to avoid clashes when the same framework is used in multiple variants inside the same workspace. I think searching subdirectories makes sense to support that.

**Comment by vinsp** [comment]
@neonichu I am using cocoapods 1.0.1 in my project so it might be it's searching for binary file in wrong folder.

**Comment by sbhklr** [comment]
@vinsp It depends on whether you are just using CocoaPods to pull in 3rd party libraries or if you are developing a Pod yourself. Since you mention `--binary-basename 'myApp'` I guess you are slathering your App's unit tests. This should work without modifications.

**Comment by vinsp** [comment]
I am using cocoapods just to pull 3rd party libraries but 'binary-basename' doesn't work as mentioned in my previous comments. It fails to search binary in sub directories. I am slathering my app unit tests

**Comment by neonichu** [comment]
@vinsp you are most likely having a different problem, then — this should only apply to slathering frameworks build via CocoaPods.

**Comment by vinsp** [comment]
@neonichu ok. I have used ```slather setup myApp.xcodeproj``` to set up project to generate code coverage.  May be I need to do some debugging in ```project.rb``` file

**Comment by sbhklr** [comment]
I think that we should print some debug information in verbose mode, about what's going on when searching the binary.

**Comment by vinsp** [comment]
Do we have any branch which has more debug logs in verbose mode? I can try to run the debug build to check exact issue.

**Comment by croccio** [comment]
ensure that in your app target -> Build Settings -> ProductName have the same value of target name
![schermata 2016-07-19 alle 10 57 13](https://cloud.githubusercontent.com/assets/3746525/16944154/93129d9c-4d9f-11e6-99b7-6e1a315379ad.png)
