### ISSUE TITLE
Unable to activate slather-2.3.0, because activesupport-5.0.0 conflicts with activesupport (< 5, >= 4.0.2)

### ISSUE THREAD

**Issue by giacgbj** [SlatherOrg/slather#239]
Is it a slather issue?

```
[11:30:14]: ▸ Error loading the plugin `slather-2.3.0`.
[11:30:14]: ▸ Gem::ConflictError - Unable to activate slather-2.3.0, because activesupport-5.0.0 conflicts with activesupport (< 5, >= 4.0.2)
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/bin/pod:22:in `load'
[11:30:14]: ▸ /Users/jhack/.rbenv/versions/2.3.0/bin/pod:22:in `<main>'
```

**Comment by neonichu** [comment]
Slather depends on `activesupport` < 5, not sure where a higher version comes from, maybe from your `Gemfile.lock`?

**Comment by gretzki** [comment]
I've got the same issue since installing Rails 5.x.
Install your gems locally for either your rails project or for your ios project which requires slather.

Cheers,
Chris

**Comment by neonichu** [comment]
Interesting, did you uninstall older versions of `activesupport` after installing Rails? If not, this sounds like a rubygems issue. In any case, using `bundler` should resolve this.

**Comment by giacgbj** [comment]
Will Slather be updated to support activesupport >=5?

**Comment by neonichu** [comment]
@giacgbj not any time soon, because removing the constraint on activesupport would mean installation with system Ruby would not work out of the box anymore.

**Comment by giacgbj** [comment]
@neonichu Is there a way to fix the version of activesupport without moving from Podfile to Gemfile?
