### ISSUE TITLE
Crash on pod install

### ISSUE THREAD

**Issue by jtreanor** [SlatherOrg/slather#240]
Slather crashes for me when using it as a CocoaPods plugin.

It seems to be crashing when locating the Xcode scheme [here](https://github.com/SlatherOrg/slather/blob/master/lib/slather/project.rb#L36). This has only occurred since updating from CocoaPods 1.0.0-> 1.0.1.

This is the error I get after `pod install`:

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/james/src/project-name/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme.rb:33:in `initialize'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme.rb:33:in `new'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme.rb:33:in `initialize'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:36:in `new'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:36:in `block in slather_setup_for_coverage'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:34:in `each'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:34:in `slather_setup_for_coverage'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/cocoapods_plugin.rb:7:in `block in <top (required)>'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:473:in `run_plugins_post_install_hooks'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:454:in `perform_post_install_actions'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:121:in `install!'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/james/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/james/.rbenv/versions/2.3.1/bin/pod:23:in `<top (required)>'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/james/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/james/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/james/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by neonichu** [comment]
Looks like a duplicate of #237 — do you still see a need for using the CP plugin of slather?

**Comment by jtreanor** [comment]
@neonichu Interesting, I didn't realise it was possible to use without the CP plugin. I give it a try.
