### ISSUE TITLE
Slather 2.3 is crashing in Xcode 8

### ISSUE THREAD

**Issue by ankitthakur** [SlatherOrg/slather#250]
Hi team, 

In Xcode 8, Slather is giving below error, during processing the code coverage:

`slather coverage --verbose`

```
 Sample-dcyxzidrnkiqrlgcwrootooawxma/Build/Intermediates/CodeCoverage/Coverage.profdata
 Against binary files:
 /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:252:in `configure': undefined method `each' for nil:NilClass (NoMethodError)
            from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:51:in `execute'
            from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
            from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
            from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
            from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
            from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
            from /usr/local/bin/slather:23:in `load'
            from /usr/local/bin/slather:23:in `<main>'
```

**Comment by ksuther** [comment]
Should be fixed by #298.
