### ISSUE TITLE
No implicit conversion of nil into String

### ISSUE THREAD

**Issue by umut-genlik** [SlatherOrg/slather#251]
Out of nowhere this command started to fail `slather coverage --html --output-directory Build/coverage` even though I can see that code coverage is generated in the folder.

![screen shot 2016-09-21 at 10 36 48 am](https://cloud.githubusercontent.com/assets/10817483/18715477/725c4d30-7fe7-11e6-8702-f4b674ec0e26.png)

I make sure I clean the DerivedData folder before each build.

But I still get the following error, and it started to happen out of no where

```
[18:42:41][Step 3/3] TypeError: no implicit conversion of nil into String
[18:42:41][Step 3/3] 	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:438:in `initialize'
[18:42:41][Step 3/3] 	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
[18:42:41][Step 3/3] 	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:438:in `new'
[18:42:41][Step 3/3] 
[18:42:41][Step 3/3] bundler: failed to load command: slather (/Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/slather)
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:438:in `block in find_binary_files'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:437:in `each'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:437:in `find_binary_files'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:344:in `configure_binary_file'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:240:in `configure'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:51:in `execute'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/slather:23:in `load'
[18:42:41][Step 3/3]   /Users/ci/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/slather:23:in `<top (required)>'
```

I also uninstall and reinstalled the slather, it didnt solve the issue.

Whats going on?

**Comment by umut-genlik** [comment]
Turns out I had to specify scheme in the .yml file, I wonder how it worked for months without scheme name and out of nowhere it started to fail

**Comment by rishbaranwal** [comment]
What is the location of .yml file, no such file is generated in my project, please guid me if I am doing wrong, I am getting above issue...

**Comment by mikelupo** [comment]
It’s not generated. You create it. And you define its contents within. The location of the file is $HOME. It’s also hidden. ls -la will list all files including the hidden ones.
