### ISSUE TITLE
fail to show code coverage report 

### ISSUE THREAD

**Issue by helenren** [SlatherOrg/slather#269]
I am running this commad: slather coverage --show --verbose ./libs/SalesforceAnalytics/SalesforceAnalytics.xcodeproj

The error got back is:

Slathering...
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path': cannot load such file -- nanaimo (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:60:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:98:in `project'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:121:in `setup_verbose_mode'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:42:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'

**Comment by helenren** [comment]
The issue is gone. Please close this. Thanks
