### ISSUE TITLE
Fail to post report from Jenkins to Coveralls

### ISSUE THREAD

**Issue by helenren** [SlatherOrg/slather#270]
Here is the errors gotten back:

21:00:29 /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
21:00:29 	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `new'
21:00:29 	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/coverage_service/coveralls.rb:189:in `post'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:91:in `post'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:53:in `execute'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
21:00:29 	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
21:00:29 	from /usr/local/bin/slather:22:in `load'
21:00:29 	from /usr/local/bin/slather:22:in `<main>'

The content of .slather.yml file I used is:

coverage_service: coveralls
ci_service: jenkins
workspace: SalesforceSDK
xcodeproj: ./SalesforceAnalytics.xcodeproj
scheme: SalesforceAnalytics
output_directory: ./test_report

If I change the coverage_service to html, or cobertura_xml, the report can be generated successfully. 

Any hint on this issue? Thanks

**Comment by helenren** [comment]
Another thing need to mention that our jenkin system is inside of a firewall, while I have set up http_proxy/https_proxy before running slather. In this case, the POST for coveralls can use that setting? Thanks
