### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by SoneeJohn** [SlatherOrg/slather#272]
I've been using slather with no problems until today I keep getting this message:

```
Slathering...
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path': cannot load such file -- nanaimo (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:60:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:98:in `project'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:59:in `setup_build_directory'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:38:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'

```
Any thoughts?

The command I've been using has remained unchanged.

**Comment by SoneeJohn** [comment]
Okay I solved the issue by reinstalling `xcodeproj` :)

**Comment by SoneeJohn** [comment]
Okay just after a couple of runs I got this:

```
/Users/soneejohn/Library/Caches/XCSBuilder/Bots/4b2c609fa833cd7b450a1d1fc3258867/Source/ALSPowerAssertionKit
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:99:in `open': [Xcodeproj] Unable to open `/Users/soneejohn/Library/Caches/XCSBuilder/Bots/4b2c609fa833cd7b450a1d1fc3258867/Source/ALSPowerAssertionKit/ALSYouTubeDownloadKit.xcodeproj` because it doesn't exist. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:60:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:98:in `project'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:71:in `setup_ignore_list'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:37:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
Slathering...
```

**Comment by SoneeJohn** [comment]
This is the script I am using:

```
usesWorkspace=false
projectName="ALSPowerAssertionKit"
schemeName="ALSPowerAssertionKit"
workspaceName=""

cd $XCS_PRIMARY_REPO_DIR

echo $XCS_PRIMARY_REPO_DIR

if [ "$usesWorkspace" = true ]

then
	/usr/local/bin/slather coverage -x --output-directory $XCS_PRIMARY_REPO_DIR/reports -i "Pods/*" -i"../**/*/Xcode*" --scheme $schemeName --workspace $workspaceName.xcworkspace --build-directory $XCS_DERIVED_DATA_DIR $projectName.xcodeproj


else
	
/usr/local/bin/slather coverage -x --output-directory $XCS_PRIMARY_REPO_DIR/reports -i "Pods/*" -i"../**/*/Xcode*" --scheme $schemeName --build-directory $XCS_DERIVED_DATA_DIR $projectName.xcodeproj

	
fi

```
