### ISSUE TITLE
Slather can't find coverage files ...

### ISSUE THREAD

**Issue by ScottYelich** [SlatherOrg/slather#278]
```
fds [125]> /usr/local/bin/slather coverage --jenkins --html --scheme JenkinsFodder JenkinsFodder.xcodeproj/
Slathering...
/Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:119:in `gcov_coverage_files': No coverage files found. (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:107:in `coverage_files'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/coverage_service/html_output.rb:26:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:91:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:53:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

Any chance slather might say WHAT it is looking for?
Any change slather might say WHERE it is looking?

Yes, I'll go modify slather source code to print out useful information.

>:-<

**Comment by ScottYelich** [comment]
There are no gcno files... Xcode doesn't generate them... that's why slather can't seem to find them.  At this point, it's time to just move on to something else... and disable slather.
