### ISSUE TITLE
Xcode 8.3.1 - `gcov_coverage_files': No coverage files found.

### ISSUE THREAD

**Issue by giacgbj** [SlatherOrg/slather#299]
It seems that after after upgrading to Xcode 8.3.1 something broke slather analysis:

```
 Exit status of command 'slather coverage --jenkins --cobertura-xml --build-directory reports/DerivedData --output-directory reports --ignore ../\* --scheme xyz --workspace zyx.xcworkspace --binary-basename xyz xyz.xcodeproj' was 1 instead of 0.
Slathering...
/Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/lib/slather/project.rb:119:in `gcov_coverage_files': No coverage files found. (StandardError)
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/lib/slather/project.rb:107:in `coverage_files'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/lib/slather/command/coverage_command.rb:91:in `post'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/lib/slather/command/coverage_command.rb:53:in `execute'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/jhack/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/slather-2.4.0/bin/slather:17:in `<top (required)>'
	from /Users/jhack/.rbenv/versions/2.4.1/bin/slather:22:in `load'
	from /Users/jhack/.rbenv/versions/2.4.1/bin/slather:22:in `<main>'
```

**Comment by ksuther** [comment]
Please try the version in master. #298 should fix this.

**Comment by giacgbj** [comment]
Thanks @ksuther, it seems to work using the latest release.
