### ISSUE TITLE
No coverage files found - when using custom derived data folder

### ISSUE THREAD

**Issue by paulz** [SlatherOrg/slather#303]
slather works for us on Jenkins when we use default xcode derived data folder.
when we set custom derived data folder for xcode

We tried setting `binary-file` and `build-directory` options:

```
slather coverage --build-directory /tmp/XcodeDerivedDataWithCoverage/ --verbose --binary-file /tmp/XcodeDerivedDataWithCoverage/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Prevent.app/Prevent
Slathering...

Processing coverage file: /tmp/XcodeDerivedDataWithCoverage/Build/Intermediates/CodeCoverage/Coverage.profdata
Against binary files:
	/tmp/XcodeDerivedDataWithCoverage/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Prevent.app/Prevent

/Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/lib/slather/project.rb:119:in `gcov_coverage_files': No coverage files found. (StandardError)
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/lib/slather/project.rb:107:in `coverage_files'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/lib/slather/coverage_service/html_output.rb:26:in `post'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:91:in `post'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:53:in `execute'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/bin/slather:23:in `load'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/bin/slather:23:in `<main>'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/bin/ruby_executable_hooks:15:in `<main>'
```

we run xcodebuild using this option:
```
xcodebuild -derivedDataPath /tmp/XcodeDerivedDataWithCoverage
```

**Comment by ksuther** [comment]
Can you update to the latest version of slather and try things again?

**Comment by paulz** [comment]
it works with slather 2.4.1, thank you!
