### ISSUE TITLE
slather cannot find Coverage.profdata file

### ISSUE THREAD

**Issue by dnedrow** [SlatherOrg/slather#319]
I've run into an issue that has me baffled.

Our build places the Coverage.profdata file at 
`/Users/********/Library/Developer/Xcode/DerivedData/Foo-gbkkvnlzoasvjceekcfkdtgnsfdp/Build/Intermediates/CodeCoverage/Coverage.profdata`

I'm pointing slather at the workspace and project using a config file.

```
coverage_service: html
input_format: profdata
workspace: ../Foo.xcworkspace
xcodeproj: Foo.xcodeproj
scheme: Foo
configuration: Debug
source_directory: Foo
ignore:
  - Unit\ Tests/*
  - AppX\ Tests/*
  - Build_scripts/*
  - MF_Protection/*
  - XcodeCoverage/*
  - build/*
output_directory: /Users/********/BuildResults/hudson/workspace/PR-Build8.0/foo/AppX/iPhone/build/buildDir/Debug-iphonesimulator/slather
source_files:
- Foo/Classes/Common/Other Classes/Abstract/FooViewModel.m
...
```

But slather doesn't seem to be able to find the coverage file.

**Comment by ksuther** [comment]
Have you tried running slather without a config file and using `--verbose` to see if you can get it finding the coverage file?

**Comment by dnedrow** [comment]
@ksuther , I'm closer. Now I'm getting an out of date error, presumably from clang?

```
>>>>> BEGIN SLATHER_PARAMS
coverage --verbose --binary-file /Users/********/BuildResults/hudson/workspace/PR-Build8.0/ios-pay/AppX/iPhone/build/buildDir/Debug-iphonesimulator/Pay.app --input-format profdata -s --scheme Pay --workspace ../Pay.xcworkspace Pay.xcodeproj
>>>>> END SLATHER PARAMS

>>>>> Running slather

Slathering...

Processing coverage file: /Users/********/Library/Developer/Xcode/DerivedData/Pay-gbkkvnlzoasvjceekcfkdtgnsfdp/Build/Intermediates/CodeCoverage/Coverage.profdata
Against binary files:
	/Users/********/BuildResults/hudson/workspace/PR-Build8.0/ios-pay/AppX/iPhone/build/buildDir/Debug-iphonesimulator/Pay.app

warning: profile data may be out of date - object is newer
[0;31merror: Failed to load coverage: Is a directory[0m
Test Coverage: NaN%
Slathered
```

**Comment by Yahsaswi** [comment]
I too have the same issue running in Xcode 7 . Please let me know of any working solution.

**Comment by dnedrow** [comment]
@ksuther, maybe I'm confused as to what --binary-file should point to. The parameter name indicates a singular file, which I assume is Foo.app? Should this be the debug Foo.app, or the Foo.app in the coverage tree?

And this is where I get a bit more confused; even though the parameter looks like it's asking for a single item, in the code it appears as though that parameter is an array. So maybe I'm just pointing at the wrong thing.

**Comment by ksuther** [comment]
It should be the app binary in CodeCoverage. So for iOS it'd be something like Foo.app/Foo and Mac it'd be Foo.app/Contents/MacOS/Foo.

You can provide multiple `--binary-file` arguments, that's why you see it as an array. This is useful if you have multiple binaries you need to generate coverage for at once (such as frameworks or libraries).

**Comment by benreic** [comment]
I'm running into a similar issue. I run slather from a small bash script, using rvm. If I call the bash script from the terminal after a build, everything works as expected. When the script is run as a Test Post-action, slather cannot find the Coverage.profdata file. Here is my bash script:

```
#!/bin/bash

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
  exit
fi

rvm install 2.3.3
rvm use 2.3.3
slather coverage --verbose --html --output-directory ./.slather-output --scheme MyiOSScheme --binary-basename Foo/Foo.framework --workspace ../../Foo.xcworkspace/ ../../Pods/Pods.xcodeproj/
```

The output I receive when running this from Xcode is as follows:

```
Slathering...
/Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:192:in `unsafe_profdata_llvm_cov_output': No Coverage.profdata files found. Please make sure the "Code Coverage" checkbox is enabled in your scheme's Test action or the build_directory property is set. (StandardError)
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:205:in `profdata_llvm_cov_output'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:126:in `block in profdata_coverage_files'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:125:in `each'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:125:in `profdata_coverage_files'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/project.rb:98:in `coverage_files'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/coverage_service/html_output.rb:26:in `post'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:93:in `post'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:55:in `execute'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/gems/slather-2.4.2/bin/slather:17:in `<top (required)>'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/bin/slather:23:in `load'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/bin/slather:23:in `<main>'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/XXXXX/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

Processing coverage file:
Against binary files:
	/Users/XXXXX/Library/Developer/Xcode/DerivedData/Foo-bqpxidcwlfsxaqcfqkwerhkvvkxj/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Foo/Foo.framework/Foo
```

Does anything jump out at you that would cause Xcode to fail with this, while having it work from the command line? Thanks for you help!

**Comment by benreic** [comment]
I figured out what was causing my issue. In my testing, Xcode does not generate the Coverage.profdata file until after the Test Post-actions are complete, so when I run my shell script, the file doesn't exist until it exits.

I can reliably test this by adding a 60 second sleep call in my script. While the script sleeps for 60 seconds, the Coverage.profdata file does not show up in the file system until the sleep is done and my script exits. 

I'll need to investigate a new place to invoke my shell script to ensure the Coverage.profdata file has already been created.
