### ISSUE TITLE
Xcode9 Beta support

### ISSUE THREAD

**Issue by athei** [SlatherOrg/slather#320]
When building with Xcode9 slather can't find the coverage data. Coverage is activated etc. I guess Xcode9 changes the path to the coverage data. My coverage resides in: `$BuildFolder/Build/ProfileData/ABEB47EF-39B4-406D-845E-29FEC58CFC62`

The contents look like this:
```
15444.profraw
15453.profraw
15460.profraw
Coverage.profdata
```

My commandline is:
`slather coverage --simple-output --scheme MyApp --workspace MyApp.xcworkspace MyApp.xcodeproj`

```
/usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:171:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:409:in `block in find_binary_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:408:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:408:in `find_binary_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:350:in `configure_binary_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:236:in `configure'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:53:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:22:in `load'
	from /usr/local/bin/slather:22:in `<main>'
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
	If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)
```

**Comment by ksuther** [comment]
PR is at #321, it'd be good to hear if it works for people.

**Comment by foobra** [comment]
same issue, I got 
```
Unknown architecture named:
Slathered
```

**Comment by ksuther** [comment]
Slather 2.4.3 has support for Xcode 9.
