### ISSUE TITLE
undefined method `to_set' for #<Array:0x007fadd2b013c8> (NoMethodError)

### ISSUE THREAD

**Issue by smarkovik** [SlatherOrg/slather#330]
Hey guys, 
not sure this is a slather issue, as I can only repro on my jenkins server, and not locally, but for some reason I get this which looks like a ruby issue. 
Can you confirm?
did anyone encounter this before?
Slather 2.4.2 (latest)
ruby 2.4.0  (both on local machine and CI) 

weird.. 
stacktrace below

Thanks! 

`
/usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:136:in `block in profdata_coverage_files': undefined method `to_set' for #<Array:0x007fadd2b013c8> (NoMethodError)
Did you mean?  to_s
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:125:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:125:in `profdata_coverage_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/project.rb:98:in `coverage_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/coverage_service/html_output.rb:26:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:93:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:55:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.2/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:22:in `load'
	from /usr/local/bin/slather:22:in `<main>'
`

**Comment by LiohAu** [comment]
I had the same issue, for now the fix was to add "require 'set'" at the top of the project.rb file...
