### ISSUE TITLE
Unable to parse test results using Cobertura 

### ISSUE THREAD

**Issue by ipodib** [SlatherOrg/slather#369]
When trying to analyze test coverage we receive this exception: 

```
Failed to read test report file {PATH}/sonar-reports/cobertura-objc.xml
org.dom4j.DocumentException: Error on line 1 of document http://cobertura.sourceforge.net/xml/coverage-04.dtd : The markup declarations contained or pointed to by the document type declaration must be well-formed. Nested exception: The markup declarations contained or pointed to by the document type declaration must be well-formed.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:132)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:302)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:244)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:175)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:154)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2719)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems that file http://cobertura.sourceforge.net/xml/coverage-04.dtd can't be parsed due to it does not exist http://cobertura.sourceforge.net/xml/coverage-04.dtdhttp://cobertura.sourceforge.net/xml/coverage-04.dtd.

How we can avoid that?

**Comment by ipodib** [comment]
Another issue already exists on Cobertura's github page: https://github.com/cobertura/cobertura/issues/366.
