### ISSUE TITLE
Error: profile data may be out of date - object is newer

### ISSUE THREAD

**Issue by m-ruhl** [SlatherOrg/slather#378]
Hello 👋 

After adding [iOSSnapshotTestCase](https://github.com/uber/ios-snapshot-test-case) Tests to my project, slather fails with this error.

```
[!] Exit status of command 'slather coverage --output-directory fastlane/test_output --ignore R.generated.\* --scheme SprIT --workspace SprIT.xcworkspace SprIT.xcodeproj' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Slathering...
warning: /Users/ci/Library/Developer/Xcode/DerivedData/SprIT-fqtuesctxzycfbgfwmyeiwmyffzc/Build/Products/Debug-iphonesimulator/SprIT.app/SprIT: profile data may be out of date - object is newer
/Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:45:in `source_file_pathname': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:197:in `ignored?'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:132:in `block (2 levels) in profdata_coverage_files'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:128:in `map'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:128:in `block in profdata_coverage_files'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:125:in `each'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:125:in `profdata_coverage_files'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/project.rb:98:in `coverage_files'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/coverage_service/simple_output.rb:17:in `post'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:97:in `post'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/ci/.rvm/gems/ruby-2.3.0/gems/slather-2.4.5/bin/slather:17:in `<top (required)>'
	from /Users/ci/.rvm/gems/ruby-2.3.0/bin/slather:23:in `load'
	from /Users/ci/.rvm/gems/ruby-2.3.0/bin/slather:23:in `<main>'
	from /Users/ci/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ci/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Have you any idea, what the problem is?

PS: I'm using Xcode 9.3

Thanks
Michael

**Comment by m-ruhl** [comment]
After I deleted the Derived data folder from Xcode it worked again
