### ISSUE TITLE
Unable to activate slather-2.4.5, because CFPropertyList-3.0.0 conflicts with CFPropertyList (~> 2.2)

### ISSUE THREAD

**Issue by giacgbj** [SlatherOrg/slather#380]
Is this a slather issue?

```
---------------------------------------------
Error loading the plugin `slather-2.4.5`.

Gem::ConflictError - Unable to activate slather-2.4.5, because CFPropertyList-3.0.0 conflicts with CFPropertyList (~> 2.2)
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:326:in `block in run'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `each'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/jhack/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/jhack/.rbenv/versions/2.5.1/bin/pod:23:in `load'
/Users/jhack/.rbenv/versions/2.5.1/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by SamuelZhaoY** [comment]
same issue here

**Comment by tzm41** [comment]
I get the same error running CocoaPods 1.5.0 commands.

**Comment by tzm41** [comment]
So is it a slather problem?

**Comment by falsecrypt** [comment]
Any updates regarding this problem? I have the same issue today.

**Comment by alvaro1728** [comment]
Any updates on this, please?!

**Comment by harsh62** [comment]
Can somebody find out why this is happening?

**Comment by mmr118** [comment]
I'm still getting issues here as well, any updates?

**Comment by bfernandesbfs** [comment]
uninstall CFPropertyList, it's work for me!

gem uninstall CFPropertyList -v 3.0

**Comment by lfap** [comment]
> uninstall CFPropertyList, it's work for me!
> 
> gem uninstall CFPropertyList -v 3.0

I'm using bitrise, where do I put this script?

**Comment by bfernandesbfs** [comment]
@lfap You can use Gemfile

**Comment by wuzhenli** [comment]
I use `gem install slather` command addressed this issue.

**Comment by xilin** [comment]
slather@2.4.7 fix this problem
