### ISSUE TITLE
Getting an error on Slathering...

### ISSUE THREAD

**Issue by marioaguzman** [SlatherOrg/slather#383]
Not sure where to begin with this error because I have a script pointing to another project and that seems to work just fine. 

/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:217:in `initialize_from_file': [Xcodeproj] Unknown object version. (RuntimeError)
from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:102:in `open'
from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.3/lib/slather/project.rb:53:in `open'
from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.3/lib/slather/command/coverage_command.rb:101:in `project'
from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.3/lib/slather/command/coverage_command.rb:70:in `setup_output_directory'
from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.3/lib/slather/command/coverage_command.rb:42:in `execute'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.3/bin/slather:17:in `<top (required)>'
from /usr/local/bin/slather:22:in `load'
from /usr/local/bin/slather:22:in `<main>'

**Comment by nicolasbenoist** [comment]
Same error for me. Did you find a solution ?

**Comment by marioaguzman** [comment]
@nicolasbenoist I believe that our dev ops engineer reverted back to Xcode 9.3.0 (from Xcode 9.3.1 at the time) and it was working all over again. I don't see how a minor dot-dot release would have changed something? Anyway, that was our work around at the time. We've recently updated to Xcode 9.4 on our build machines and I haven't seen this issue re-surface. I will report back if it has.

**Comment by TimchenKKBOX** [comment]
I had encountered the same problem, and run below command can work
`gem install xcodeproj`
