### ISSUE TITLE
Script fails ( undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by MetaImi** [SlatherOrg/slather#397]
When I'm running slather, I get this error for Xcode 9.3 / 9.4. 
It is working for 9.2. 

Slathering...
/Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:45:in `source_file_pathname': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:197:in `ignored?'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:132:in `block (2 levels) in profdata_coverage_files'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:128:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:128:in `block in profdata_coverage_files'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:125:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:125:in `profdata_coverage_files'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/project.rb:98:in `coverage_files'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:97:in `post'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.5/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:22:in `load'
	from /usr/local/bin/slather:22:in `<main>'

**Comment by MetaImi** [comment]
I also installed from master

**Comment by trybekd** [comment]
I've encountered same issue

**Comment by kgenoe** [comment]
Getting this same issue as of Xcode 9.4

**Comment by Sicness** [comment]
```
slather coverage --input-format profdata --cobertura-xml --output-directory sonar-reports --workspace RASM_Tests/RASM_Tests.xcworkspace --scheme RASM_Tests RASM_Tests/RASM_Tests.xcodeproj
Slathering...
/Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:45:in `source_file_pathname': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/profdata_coverage_file.rb:197:in `ignored?'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:132:in `block (2 levels) in profdata_coverage_files'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:128:in `map'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:128:in `block in profdata_coverage_files'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:125:in `each'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:125:in `profdata_coverage_files'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/project.rb:98:in `coverage_files'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:97:in `post'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/gems/slather-2.4.5/bin/slather:17:in `<top (required)>'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/bin/slather:23:in `load'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/bin/slather:23:in `<main>'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/abalashov/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

$ slather version
slather 2.4.5
```

**Comment by ezisazis** [comment]
Same here, is there any progress on it? 🤔

**Comment by SlaunchaMan** [comment]
Also getting this in Xcode 10

**Comment by SlaunchaMan** [comment]
After some more investigation, I was able to fix this by adding a method to an empty class. We had a `ViewController` just sitting there with no methods (yet):

```Swift
class ViewController: UIViewController {

}
```

Adding an empty `viewDidLoad()` prevented this problem from reoccurring:

```Swift
class ViewController: UIViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
	}

}
```

Now we’re getting coverage without crashes.

**Comment by matzino** [comment]
Same here ... did somebody has a solution for that error?

**Comment by ksuther** [comment]
@matzino Please try the version of slather in master. It includes #398 and should fix this.

**Comment by matzino** [comment]
@ksuther Thank you, it seems to be working well with the master branch.

**Comment by trybekd** [comment]
Everything works after upgrading to version 2.4.6

**Comment by matzino** [comment]
@trybekd I made an update and got the version 2.4.5 on these days, did you release in the meantime a new version? Then I will update too ;)

**Comment by trybekd** [comment]
@matzino I've installed it using `gem install slather` and it upgraded to 2.4.6

**Comment by dmazzoni** [comment]
I am currently experiencing this issue with Slather 2.4.6 and Xcode 10.1 (10B61) with the same stack trace:

```
Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/profdata_coverage_file.rb:45:in `source_file_pathname': undefined method `each' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/profdata_coverage_file.rb:197:in `ignored?'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:139:in `block (2 levels) in profdata_coverage_files'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:135:in `map'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:135:in `block in profdata_coverage_files'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `each'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `profdata_coverage_files'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/project.rb:98:in `coverage_files'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/coverage_service/html_output.rb:26:in `post'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:97:in `post'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:59:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.6/bin/slather:17:in `<top (required)>'
    from /usr/local/bin/slather:22:in `load'
    from /usr/local/bin/slather:22:in `<main>'
```

I am invoking Slather with Fastlane, after performing `clear_derived_data` and `scan` with coverage enabled (and `clean: true`).

An interesting fact is that this happens only if I checkout the project at a different location, but everything works if I call Fastlane from the project's original working directory, even though the `.slather.yml` file I am using contains only relative paths.

**Comment by 1oo7** [comment]
Getting `branch_coverage_data': undefined method `each' for nil:NilClass (NoMethodError)` on Xcode 12.5 all of a sudden. Not on 12.3 though.
