### ISSUE TITLE
JSON ParserError on version 2.4.6

### ISSUE THREAD

**Issue by ajpagente** [SlatherOrg/slather#405]
**When running slather version 2.4.6 I get the error below. The issue is not there on v2.4.5 and 2.4.4. Unfortunately I am not able to share the xcode project and binary file (company rules). However I am willing to help test intermediate fixes. Do let me know if you need additional information.** 

slather coverage -s --scheme MyLibTest --binary-file ../sdk/build/Intermediates/CodeCoverage/Intermediates/MyLib.build/Debug-iphonesimulator/MLibTestTests.build/Objects-normal/x86_64/MyLibTestTests  ../sdk/MyLib.xcodeproj
Slathering...
Unrecognized command: export.

Usage: llvm-cov {gcov|report|show} [OPTION]...

Shows code coverage information.

Subcommands:
  gcov:   Work with the gcov format.
  show:   Annotate source files using instrprof style coverage.
  report: Summarize instrprof style coverage information.
Traceback (most recent call last):
	15: from /usr/local/bin/slather:23:in `<main>'
	14: from /usr/local/bin/slather:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/bin/slather:17:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:59:in `execute'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:97:in `post'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/coverage_service/simple_output.rb:17:in `post'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:98:in `coverage_files'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `profdata_coverage_files'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `each'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:126:in `block in profdata_coverage_files'
	 1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)

**Comment by kerimovscreations** [comment]
Check the comment for further hints: 
https://github.com/SlatherOrg/slather/issues/495#issuecomment-1079844546
