### ISSUE TITLE
Static Framework error: "Failed to load coverage: Malformed coverage data"

### ISSUE THREAD

**Issue by drhaynes** [SlatherOrg/slather#408]
Steps to reproduce:
1. Create an Xcode iOS framework project  
2. Change the config to build a static framework (default is dynamic)
3. Add some code, and tests, run them
4. Try to slather, fails with error:

```
Slathering...
warning: /Users/someone/Library/Developer/Xcode/DerivedData/ExampleProject-dfhqckbsbbplngbpdgzkcrydokby/Build/Products/Debug-iphonesimulator/Example.framework/Example: profile data may be out of date - object is newer
error: /Users/someone/Library/Developer/Xcode/DerivedData/ExampleProject-dfhqckbsbbplngbpdgzkcrydokby/Build/Products/Debug-iphonesimulator/Example.framework/Example: Failed to load coverage: Malformed coverage data
error: Could not load coverage information
Traceback (most recent call last):
	15: from /usr/local/bin/slather:23:in `<main>'
	14: from /usr/local/bin/slather:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/bin/slather:17:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:59:in `execute'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:97:in `post'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:98:in `coverage_files'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `profdata_coverage_files'
```

It seems that, because the library is statically linked into the test bundle, coverage is not calculated for the framework target itself.

Additionally, if you tell Xcode to show you the coverage for test bundles (by ticking "Show Test Bundles") then you can see the combined coverage of the unit tests, and the framework code.

Seems to be related to:
http://www.openradar.me/41024315

Wondering if there's a workaround/solution for this?

**Comment by neisip** [comment]
Same here:
Trying to run SonarQube with open source Swift-Lint plugin. Slather there is mandatory.
What I get is:

```
slather coverage --binary-basename MyCore --input-format profdata -i Pods -i MyCore -i infer-out --cobertura-xml --output-directory sonar-reports --workspace MyCore.xcworkspace --scheme MyCore MyCore.xcodeproj
Slathering...
error: /Users/me/Library/Developer/Xcode/DerivedData/MyCore-fiplkghilnltujchqdfgmqrajnhg/Build/Products/Debug-iphonesimulator/MyCore.framework/MyCore: Failed to load coverage: Malformed coverage data
error: Could not load coverage information
Traceback (most recent call last):
	15: from /usr/local/bin/slather:23:in `<main>'
	14: from /usr/local/bin/slather:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/bin/slather:17:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:59:in `execute'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/command/coverage_command.rb:97:in `post'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:98:in `coverage_files'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `profdata_coverage_files'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:124:in `each'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/slather-2.4.6/lib/slather/project.rb:126:in `block in profdata_coverage_files'
	 1: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
MBP:MyCore me$ 
```

And what I found is that actually, Coverage.profdata is being generated in Build/ProfileData folder, while slather looks at MyCore.framework/MyCore

@drhaynes Hopefully you could help us, as I will need to dig a huge workaround otherwise.

**Comment by levantAJ** [comment]
Run into same problem!

**Comment by pddkhanh** [comment]
@levantAJ  I got the same problem but found out it's because I have multiple Xcode versions (10.3 and 10.2.1) and didn't configure it correctly so it was built and tested with different versions. It worked after I changed to use 10.2.1 for all steps.

It's a small world.

**Comment by cooler333** [comment]
just configure binary_basename

**Comment by wangbingwf** [comment]
I have the same problem, and found the reason.it is caused by llvm, not slather
to generate xml, slather use  `llvm-cov ` cmd, but it's not work with static library

so i add ` MACH_O_TYPE=mh_dylib` to `xcodebuild test` to generate a dynamic library, and slather will work well.

**Comment by daxios-learn** [comment]
Anyone manage to solve this issue ? 

The weird thing is, XCode can show the coverage properly. ;

**Comment by aelam** [comment]
guys, currently im using this solution 
https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700

**Comment by fangmobile** [comment]
non of the solution above worked for me. 
I am building a static framework and testing it in another app/unit test.
--binary does not work. If I open derived data for this, the `Module` is a `document`, while other dynamic frameworks are all `unit executable`.

**Comment by aelam** [comment]
> non of the solution above worked for me. 
> I am building a static framework and testing it in another app/unit test.
> --binary does not work. If I open derived data for this, the `Module` is a `document`, while other dynamic frameworks are all `unit executable`.

@fangmobile you need to set the binary as the app one

**Comment by fangmobile** [comment]
> @fangmobile you need to set the binary as the app one

I believed I tried that back in April.
There is another issue about the same.
