### ISSUE TITLE
Xcode10 pod install fail

### ISSUE THREAD

**Issue by yanzhiwei147** [SlatherOrg/slather#417]
When i append the `plugin 'slather'` to `Podfile` and run `pod update`, it will crash. attach the crash log below:

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/arida/Develop/source/gerrit.sdp.nd/Appfactory/APFKit/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/arida/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.9/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.9/lib/xcodeproj/scheme.rb:34:in `new'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.9/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/slather-2.4.6/lib/slather/project.rb:33:in `new'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/slather-2.4.6/lib/slather/project.rb:33:in `block in slather_setup_for_coverage'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/slather-2.4.6/lib/slather/project.rb:31:in `each'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/slather-2.4.6/lib/slather/project.rb:31:in `slather_setup_for_coverage'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/slather-2.4.6/lib/cocoapods_plugin.rb:8:in `block in <top (required)>'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:489:in `run_plugins_post_install_hooks'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:467:in `perform_post_install_actions'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:147:in `install!'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/command/update.rb:97:in `run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/arida/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/arida/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/arida/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/arida/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/arida/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

- I review the [Slather for Cocoapods plugin](https://github.com/SlatherOrg/slather/blob/6ff2a539154662edc5026a5009fba58b38e4930c/lib/cocoapods_plugin.rb#L4) and append debug log message.
- The `installer_context.sandbox_root` always be `/path/to/Pods/Pods.xcodeproj`
- The `Pods.xcodeproj ` was generated by Cocoapods but not generate `xcshareddata/xcschemes/Pods.xcscheme`.
- So it will crash on my example project.

Related issue but not working for me: #237   

I can append message if project team need more infomations.

**Comment by sirghi** [comment]
Same here
