### ISSUE TITLE
Fail test code coverage not found coverage directory in Xcode 10.1

### ISSUE THREAD

**Issue by amine2233** [SlatherOrg/slather#418]
Can't show code coverage in my Mac and in my Jenkins,

```bash
bundle exec slather coverage -s --scheme "Reactive iOS" --workspace Reactive.xcworkspace Reactive.xcodeproj/
```

Result

```bash
Slathering...
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)

bundler: failed to load command: slather (/Users/amine/.rbenv/versions/2.5.3/bin/slather)
StandardError: No coverage directory found.
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:178:in `profdata_coverage_dir'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:403:in `block in find_binary_files'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:402:in `each'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:402:in `find_binary_files'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:348:in `configure_binary_file'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/project.rb:242:in `configure'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/lib/slather/command/coverage_command.rb:51:in `execute'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
  /Users/amine/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/slather-2.4.0/bin/slather:17:in `<top (required)>'
  /Users/amine/.rbenv/versions/2.5.3/bin/slather:23:in `load'
  /Users/amine/.rbenv/versions/2.5.3/bin/slather:23:in `<top (required)>'
```

**Comment by IPrototypeI** [comment]
@amine2233 

Hi I had the same problem, please use the newest version 2.4.6 , if you try to install the dependencies ruby install by default version 2.4.0

https://rubygems.org/gems/slather

**Comment by cesar-oyarzun-m** [comment]
Hi @amine2233 I'm having the same issue with Xcode 10.1, now looks like the coverage report is inside a folder with the timestamp, I think that is why slather can't find the report files, Where you able to fix it?. @IPrototypeI I did try the version 2.4.6 still having same issue.

**Comment by billburgess** [comment]
I'm running 2.4.7 and still having the same issue.

**Comment by vjmaiky** [comment]
running into to the same issue on 2.4.7...any ideas?

**Comment by lucasvercelot** [comment]
Hi ! 👋 
Any update on this issue ?

**Comment by badrinathvm** [comment]
I am also facing the same issue on Xcode 10.1

**Comment by corteggo** [comment]
It happens with Xcode 11 beta 1 & 2 as well.

**Comment by agronauts** [comment]
Using XCode 10.1 & Slather 2.4.7 I encountered this and got around it by having relative path specified for `-derivedDataPath` in the xcodebuild command and `build_directory` in the .slather.yaml file.

I also found specifying the `slather --arch` flag to something in your project -> Build Settings -> Valid Architectures setting (Eg. arm64) intermittently solved this, but wasn't necessary in the end.

Hope this helps :)

**Comment by y8k** [comment]
I had same error state on Xcode 10.2..

**Comment by huipengo** [comment]
I had same error state on Xcode 10.2. 
slather 2.4.7. 
ruby-2.5.3

how to fix it ?

**Comment by MZapatae** [comment]
Same error with Xcode11. Appearly I think is the option to generate code coverage is not present in this version.

Xcode 10
<img width="300" alt="Captura de Pantalla 2019-09-24 a la(s) 13 59 22" src="https://user-images.githubusercontent.com/1772787/65533240-a806e280-ded3-11e9-8c45-24c385453a91.png">

Xcode 11
<img width="373" alt="Captura de Pantalla 2019-09-24 a la(s) 14 01 01" src="https://user-images.githubusercontent.com/1772787/65533323-c40a8400-ded3-11e9-8650-92caddd7c8f1.png">

**Comment by popmedic** [comment]
@MZapatae it is under options.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/1749349/66233915-a0042b00-e6a9-11e9-8ccf-f2b9ea2e8f17.png">
That said, I am getting this same error with Xcode 11

**Comment by leandroromn** [comment]
I had same error here running with Fastlane.

Xcode 11.2.1
Slather 2.4.7
Ruby 2.6.3p62

Any update?

**Comment by Speakus** [comment]
could anyone suggest alternative for slather since it does not work with Xcode 11?

**Comment by dileep017** [comment]
Can anyone suggest is there any solution for this? It is still happening with,Xcode Version 11.3.1 (11C505)
gems used is 3.0.3 and slather (2.4.8, 2.4.7)

**Comment by mayoralito** [comment]
Same happening to me, any clue? The same configuration was working fine in other versions of Xcode 10.x.x:
```
macOS: 10.15.5 (19F101)
Xcode: Version 11.5 (11E608c)
❯ slather version: 2.4.9
```

**Comment by DonnieLi** [comment]
I can genergate report when i use Xcode run UITest. But use command line run,it does not work. any ideas? Thx

**Comment by 1ucas** [comment]
Same here on XCode 12.
By the way, when I run my tests on XCode, my coverage reports are being generated at the default  XCode derived data.
But slather doesn't know this path. Maybe that's the problem? 
Or does Slather rebuild the selected scheme by itself?

**Comment by jambudi** [comment]
I have a same error for xcode 12.2

**Comment by rick711003** [comment]
I have a same error for Xcode 14.2

**Comment by salvatoreboemia** [comment]
Same issue starting from Xcode 14.3.x and Xcode 15

No news on this?
