### ISSUE TITLE
Unable to slather

### ISSUE THREAD

**Issue by jsaini-hw** [SlatherOrg/slather#433]
Getting following error when doing slather through travis ci

`Slathering...
/Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/json/common.rb:156:in `parse': 751: unexpected token at '<h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>' (JSON::ParserError)
	from /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/coverage_service/coveralls.rb:224:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:97:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:140:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/bin/slather:17:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/slather:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/slather:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'`

**Comment by jsaini-hw** [comment]
Now started getting the following error
`if [ "$code_coverage" == "YES" ]; then slather; fi
Slathering...
 (JSON::ParserError)
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
	from /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/coverage_service/coveralls.rb:224:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:97:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/clamp-1.3.1/lib/clamp/command.rb:140:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/slather-2.4.7/bin/slather:17:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/slather:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/slather:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'`

**Comment by JanGorman** [comment]
We pinned this down to _some_ difference between macOS Mojave and Catalina. It fails to parse JSON on Catalina
