### ISSUE TITLE
Installing the slather plugin in cocoa pods

### ISSUE THREAD

**Issue by 463292462** [SlatherOrg/slather#435]

**Comment by Speakus** [comment]
Put it into Gemfile and use `bundle install` command. cause it's not cocoapod but gem.

**Comment by andresilveirah** [comment]
I'm having the same issue. 
```
# podfile
use_frameworks!
platform :ios, '9.0'
plugin 'cocoapods-repo-update'
plugin 'slather'

target 'MyProject' do
  pod 'MyPod', :path => '../'
end
```
```
#gemfile
source 'https://rubygems.org'

gem 'cocoapods'
gem 'cocoapods-repo-update'
gem 'slather'
```
```
#.slather.yml
coverage_service: cobertura_xml
workspace: Example/MyProject.xcworkspace
xcodeproj: Example/MyProject.xcodeproj
scheme: MyProject
source_directory: Pods/ConsentViewController
output_directory: coverage/
```

Running `bundle install` works.

When I run `pod install` I get: 
```
Checking if specs repo should be updated
Not updating local specs repo
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/andreherculano/.rvm/gems/ruby-2.6.5/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/andreherculano/.rvm/rubies/ruby-2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ e5dd21dde3581f1fe73915ce221713b6f6f15858

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-repo-update : 0.0.4
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
slather               : 2.4.9
```

### Podfile

```ruby
use_frameworks!
platform :ios, '9.0'
plugin 'cocoapods-repo-update'
plugin 'slather'

target 'MyProject' do
  pod 'MyPod', :path => '../'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - [redacted]/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/xcodeproj-1.17.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/xcodeproj-1.17.0/lib/xcodeproj/scheme.rb:34:in `open'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/xcodeproj-1.17.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/slather-2.4.9/lib/slather/project.rb:33:in `new'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/slather-2.4.9/lib/slather/project.rb:33:in `block in slather_setup_for_coverage'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/slather-2.4.9/lib/slather/project.rb:31:in `each'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/slather-2.4.9/lib/slather/project.rb:31:in `slather_setup_for_coverage'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/slather-2.4.9/lib/cocoapods_plugin.rb:7:in `block in <top (required)>'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:115:in `each'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:114:in `run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:632:in `run_plugins_post_install_hooks'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:607:in `perform_post_install_actions'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:165:in `install!'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/bin/pod:23:in `load'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/bin/pod:23:in `<main>'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/andreherculano/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
```

Perhaps the real issue is in:
```
Errno::ENOENT - No such file or directory @ rb_sysopen - [redacted]/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
```

But I'm not sure how to solve it. Not sure why the `Pods.xcscheme` file is missing or how to create it.

**Comment by andresilveirah** [comment]
Perhaps this is a duplicate of #417
