### ISSUE TITLE
Unable to slather when importing a static framework using Carthage

### ISSUE THREAD

**Issue by dalu93** [SlatherOrg/slather#439]
Hi all,

I'm trying to slather my project after running the test sets, but I encountered the following error:

`/Users/MY_USER/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slather-2.4.7/lib/slather/project.rb:138:in `realpath': No such file or directory @ realpath_rec - /Users/MY_USER/Desktop/MY_PROJECT/Carthage/Checkouts/appcenter-sdk-apple (Errno::ENOENT)`

My setup is the following:

- Carthage
`github "microsoft/appcenter-sdk-apple"`

- Rome
```
Cache]
  local = ~/Library/Caches/Rome/

[RepositoryMap]
  appcenter-sdk-apple = static/AppCenter, static/AppCenterCrashes
```

- Fastlane
```
desc "Runs all the tests without rebuilding"
  lane :test do
    run_tests(
      scheme: "Dev",
      configuration: "Dev-Debug",
      code_coverage: true
    )

    prepare_coverage_reports
  end

  desc "Prepares coverage reports"
  lane :prepare_coverage_reports do
    slather(
      build_directory: lane_context[SharedValues::SCAN_DERIVED_DATA_PATH],
      binary_basename: "MY_PRODUCT_DIR",
      scheme: "Dev",
      proj: "MY_PRODUCT.xcodeproj",
      cobertura_xml: true,
      jenkins: true,
      output_directory: "build/coverage",
      ignore: [
        '*ViewController.swift', 
        '*Cell.swift',
        '*View.swift',
        'Carthage/*'
      ]
    )

    convert_code_coverage_for_sonar
  end
```

Of course, I'm hiding the other libraries, but before adding `appcenter-sdk-apple` as a static framework, everything used to work fine.
Additionally, the `Carthage/Checkouts` folder is completely empty, since I'm using `Rome` to download the dependencies locally.

I'm not sure why `slather` started digging in that folder now.

Below my Gemfile.lock if needed

```
GEM
  remote: http://rubygems.org/
  specs:
    CFPropertyList (3.0.1)
    activesupport (4.2.11.1)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    atomos (0.1.3)
    babosa (1.0.3)
    badge (0.11.0)
      curb (~> 0.9)
      fastimage (>= 1.6)
      fastlane (>= 2.0)
      mini_magick (~> 4.9.5)
    claide (1.0.3)
    clamp (1.3.1)
    colored (1.2)
    colored2 (3.1.2)
    commander-fastlane (4.4.6)
      highline (~> 1.7.2)
    concurrent-ruby (1.1.5)
    curb (0.9.10)
    declarative (0.0.10)
    declarative-option (0.1.0)
    digest-crc (0.4.1)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.5)
    emoji_regex (1.0.1)
    excon (0.68.0)
    faraday (0.17.0)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    faraday_middleware (0.13.1)
      faraday (>= 0.7.4, < 1.0)
    fastimage (2.1.7)
    fastlane (2.136.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.3, < 3.0.0)
      babosa (>= 1.0.2, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander-fastlane (>= 4.4.6, < 5.0.0)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 2.0)
      excon (>= 0.45.0, < 1.0.0)
      faraday (~> 0.17)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 0.13.1)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-api-client (>= 0.21.2, < 0.24.0)
      google-cloud-storage (>= 1.15.0, < 2.0.0)
      highline (>= 1.7.2, < 2.0.0)
      json (< 3.0.0)
      jwt (~> 2.1.0)
      mini_magick (>= 4.9.4, < 5.0.0)
      multi_xml (~> 0.5)
      multipart-post (~> 2.0.0)
      plist (>= 3.1.0, < 4.0.0)
      public_suffix (~> 2.0.0)
      rubyzip (>= 1.3.0, < 2.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      slack-notifier (>= 2.0.0, < 3.0.0)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.8.1, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-appcenter (1.7.0)
    fastlane-plugin-sentry (1.6.0)
    gh_inspector (1.1.3)
    google-api-client (0.23.9)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.9)
    google-cloud-core (1.4.1)
      google-cloud-env (~> 1.0)
    google-cloud-env (1.3.0)
      faraday (~> 0.11)
    google-cloud-storage (1.16.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.23)
      google-cloud-core (~> 1.2)
      googleauth (>= 0.6.2, < 0.10.0)
    googleauth (0.6.7)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.7)
    highline (1.7.10)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    json (2.2.0)
    jwt (2.1.0)
    memoist (0.16.1)
    mime-types (3.3)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2019.1009)
    mini_magick (4.9.5)
    mini_portile2 (2.4.0)
    minitest (5.13.0)
    multi_json (1.14.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nanaimo (0.2.6)
    naturally (2.2.0)
    nokogiri (1.10.5)
      mini_portile2 (~> 2.4.0)
    os (1.0.1)
    plist (3.5.0)
    public_suffix (2.0.5)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rouge (2.0.7)
    rubyzip (1.3.0)
    security (0.1.3)
    signet (0.12.0)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.6)
      CFPropertyList
      naturally
    slack-notifier (2.3.2)
    slather (2.4.7)
      CFPropertyList (>= 2.2, < 4)
      activesupport (>= 4.0.2, < 5)
      clamp (~> 1.3)
      nokogiri (~> 1.8)
      xcodeproj (~> 1.7)
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    tty-cursor (0.7.0)
    tty-screen (0.7.0)
    tty-spinner (0.9.1)
      tty-cursor (~> 0.7)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.6)
    unicode-display_width (1.6.0)
    word_wrap (1.0.0)
    xcodeproj (1.13.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.2.6)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.0)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  badge
  fastlane
  fastlane-plugin-appcenter
  fastlane-plugin-sentry
  slather

BUNDLED WITH
   2.0.2
```

**Comment by pbradly** [comment]
We've just come across the same issue as well. Did you ever solve it or is it still an issue?

**Comment by dalu93** [comment]
@pbradly We switched from static to dynamic framework and it fixed the issue.

**Comment by Adnan-Sky** [comment]
I am getting the same issue, anyone found a a fix apart form switching to dynamic framework.

**Comment by anhbontb** [comment]
I have same issue.
My app using rome and carthage to cache static framework. 
I have work around by clone this repose and update some code in project.rb file.
Here my code.
Hope this will help some one
`
 def pathnames_per_binary(binary_path)
      coverage_json_string = llvm_cov_export_output(binary_path)
      coverage_json = JSON.parse(coverage_json_string)
      coverage_json["data"].reduce([]) do |result, chunk|
        result.concat(chunk["files"].map do |file|
          
          begin
            Pathname(file["filename"]).realpath
          rescue Errno::ENOENT
            puts file["filename"]
            puts "could not find this file on current computer"
          end          
        end)
      end
    end
`

**Comment by fangmobile** [comment]
Getting similar error when setting a framework as `static_framework= true` in Podfile with Cocoapods. I am assuming this is caused by same bug?
```Failed to load coverage: No coverage data found
error: Could not load coverage information
Traceback (most recent call last):
	18: from /Users/xxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	17: from /Users/xxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	16: from /Users/xxx/.rvm/gems/ruby-2.7.2/bin/slather:23:in `<main>'
	15: from /Users/xxx/.rvm/gems/ruby-2.7.2/bin/slather:23:in `load'
	14: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/bin/slather:17:in `<top (required)>'
	13: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	12: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	11: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	10: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	 9: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/command/coverage_command.rb:61:in `execute'
	 8: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/command/coverage_command.rb:101:in `post'
	 7: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	 6: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/project.rb:98:in `coverage_files'
	 5: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/project.rb:123:in `profdata_coverage_files'
	 4: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/project.rb:123:in `each'
	 3: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/project.rb:124:in `block in profdata_coverage_files'
	 2: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/slather-2.6.0/lib/slather/project.rb:135:in `pathnames_per_binary'
	 1: from /Users/xxx/.rvm/gems/ruby-2.7.2/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/Users/xxx/.rvm/gems/ruby-2.7.2/gems/json-2.5.1/lib/json/common.rb:216:in `parse': 809: unexpected token at '' (JSON::ParserError)
```

I am using `--binary-basename` to test different modules. same command works for any dynamic framework modules. As soon as I run the command with this static framework, it gets above error.
