### ISSUE TITLE
Problem in new version 2.7.0

### ISSUE THREAD

**Issue by rbrovko** [SlatherOrg/slather#480]
New version broken CI/CD.
Project with swift code.

```
Slathering...
1847/Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:204:in `block (8 levels) in create_html_from_file': undefined method `split' for nil:NilClass (NoMethodError)
1848	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:203:in `each'
1849	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:203:in `block (7 levels) in create_html_from_file'
1850	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:395:in `insert'
1851	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:378:in `method_missing'
1852	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:190:in `block (6 levels) in create_html_from_file'
1853	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:395:in `insert'
1854	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:378:in `method_missing'
1855	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:189:in `block (5 levels) in create_html_from_file'
1856	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:185:in `each'
1857	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:185:in `each_with_index'
1858	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:185:in `block (4 levels) in create_html_from_file'
1859	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:395:in `insert'
1860	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:378:in `method_missing'
1861	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:184:in `block (3 levels) in create_html_from_file'
1862	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:174:in `each'
1863	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:174:in `block (2 levels) in create_html_from_file'
1864	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:395:in `insert'
1865	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:378:in `method_missing'
1866	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:173:in `block in create_html_from_file'
1867	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:296:in `initialize'
1868	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:255:in `new'
1869	from /Users/ci/.gem/ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/builder.rb:255:in `with'
1870	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:154:in `create_html_from_file'
1871	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:140:in `block in create_htmls_from_files'
1872	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:140:in `map'
1873	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:140:in `create_htmls_from_files'
1874	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:49:in `create_html_reports'
1875	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/coverage_service/html_output.rb:26:in `post'
1876	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/command/coverage_command.rb:101:in `post'
1877	from /Users/ci/.gem/gems/slather-2.7.0/lib/slather/command/coverage_command.rb:61:in `execute'
1878	from /Users/ci/.gem/ruby/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
1879	from /Users/ci/.gem/ruby/2.6.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
1880	from /Users/ci/.gem/ruby/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
1881	from /Users/ci/.gem/ruby/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
1882	from /Users/ci/.gem/gems/slather-2.7.0/bin/slather:17:in `<top (required)>'
1883	from /Users/ci/.gem/bin/slather:23:in `load'
1884	from /Users/ci/.gem/bin/slather:23:in `<main>'
```

**Comment by ksuther** [comment]
Thanks for the report. Do you have a test case to try to reproduce this?
