### ISSUE TITLE
"error: Could not load coverage information" on targets with 0% code coverage

### ISSUE THREAD

**Issue by Tovkal** [SlatherOrg/slather#495]
I am getting this error on targets that have no coverage because they have no tests and don't know if this is expected behavior or not.

```
error: .../DerivedData/Build/Products/Debug-iphonesimulator/SomeModule.framework/SomeModule: Failed to load coverage: No coverage data found
error: Could not load coverage information
/Users/someUser/.gems/gems/json-2.5.1/lib/json/common.rb:216:in `parse': 809: unexpected token at '' (JSON::ParserError)
	from /Users/someUser/.gems/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/project.rb:135:in `pathnames_per_binary'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/project.rb:124:in `block in profdata_coverage_files'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/project.rb:123:in `each'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/project.rb:123:in `profdata_coverage_files'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/project.rb:98:in `coverage_files'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/coverage_service/sonarqube_xml_output.rb:18:in `post'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/command/coverage_command.rb:101:in `post'
	from /Users/someUser/.gems/gems/slather-2.7.0/lib/slather/command/coverage_command.rb:61:in `execute'
	from /Users/someUser/.gems/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/someUser/.gems/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/someUser/.gems/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/someUser/.gems/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /Users/someUser/.gems/gems/slather-2.7.0/bin/slather:17:in `<top (required)>'
	from /Users/someUser/.gems/bin/slather:23:in `load'
	from /Users/someUser/.gems/bin/slather:23:in `<main>'
```

I am trying to run slather on a multi module project, all living under one workspace. The command I am running (by using the fastlane plugin) is a more complex version of the following, where I pass all targets I want coverage on as `--binary-basename` parameters.

`slather coverage --sonarqube-xml --build-directory DerivedData --output-directory DerivedData/slatherOutput --ignore Pods/\* --ignore Frameworks/\* --scheme MyApp-ALL-TESTS --workspace ./MyApp.xcworkspace --binary-basename MyApp --binary-basename SomeModule  ./MyApp.xcodeproj`

**Comment by kerimovscreations** [comment]
Make sure:

1. All modules are included in the test phase of the main scheme

<img width="931" alt="Screen Shot 2022-03-27 at 09 31 23" src="https://user-images.githubusercontent.com/10672530/160268212-a0ee80d5-ae10-46d4-ba14-7983dd2bedbc.png">

<img width="927" alt="Screen Shot 2022-03-27 at 09 34 32" src="https://user-images.githubusercontent.com/10672530/160268262-0ced0ad1-5e70-44bc-8dce-02525b443aa5.png">


2. All modules and their test modules are configured as `Enable Testability: True`

<img width="872" alt="Screen Shot 2022-03-27 at 09 32 21" src="https://user-images.githubusercontent.com/10672530/160268222-1a4c21bb-3024-49db-8661-04d68f0bf890.png">

Example of project building:

```
xcodebuild \
          -project yourproject.xcodeproj/ \
          -scheme yourproject \
          -derivedDataPath Build/ \
          -enableCodeCoverage YES \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES \
          VALID_ARCHS=x86_64 \
          OBJROOT="$PWD/Build" \
          SYMROOT="$PWD/Build" \
          clean \
          build \
          test
```

Slather generator:

```
slather coverage --sonarqube-xml \
          --build-directory Build \
          --output-directory sonar-reports \
          --scheme retail-mobile-bank retail-mobile-bank.xcodeproj
```

**Comment by taher-mosbah** [comment]
Is there any updates on this one ? we started getting the same error when running on Xcode 16 beta.

**Comment by Cynthia1991** [comment]
We have similar issues when build with Xcode 16 beta 4:
```
error: Failed to load coverage: 'XXXXXX': No coverage data found
error: Could not load coverage information
```
Any updates from this one?

**Comment by MadanG222** [comment]
Even I am facing same issue. This is working on xCode 15.4 and older but xCode 16 beta 5, I am getting same error. let me know if anyone know any solution for this.

**Comment by jarrodlombardo-EventBase** [comment]
I can't test this issue myself (If I upgrade beyond XCode 15.1 currently, it will break things for me at work), but if anyone running XCode 16 can get any more detailed information about what has changed in XCode between 15.x and 16, that could help. There was a breaking change in the LLDB version XCode was using between XCode 14.2 and 14.3 that broke lots of things, so maybe they did something similar between XCode 15 and 16.

**Comment by juxia0809** [comment]
Any update on this issue? we are also facing this issue now.

**Comment by muhammadsalmananwaar-gif** [comment]
Any update on this?

**Comment by jarrodlombardo-EventBase** [comment]
XCode 16.2 had a breaking change in LLDB and ALL of your frameworks need to be built with XCode 16.2+ or all of them need to be built with older (but not too old) XCode for coverage to work. https://developer.apple.com/forums/thread/770289?answerId=853752022#853752022
This is unrelated to Slather, but since slather relies on the LLDB/XCode output, it breaks slather.
