### ISSUE TITLE
Xcode 12.5 `profdata_coverage_dir': No coverage directory found. (StandardError)😇

### ISSUE THREAD

**Issue by keisukeYamagishi** [SlatherOrg/slather#497]
I executed following command.
I got a error and error log
Does anyone know how to solve this problem?

```
->> slather coverage --html --scheme sevens --workspace apps.xcworkspace apps.xcodeproj
Slathering...
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
	If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)

Traceback (most recent call last):
	11: from /usr/local/bin/slather:23:in `<main>'
	10: from /usr/local/bin/slather:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/bin/slather:17:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	 5: from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/lib/slather/command/coverage_command.rb:59:in `execute'
	 3: from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/lib/slather/project.rb:336:in `configure'
	 2: from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/lib/slather/project.rb:456:in `configure_binary_file'
	 1: from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/lib/slather/project.rb:517:in `find_binary_files'
/Library/Ruby/Gems/2.6.0/gems/slather-2.7.1/lib/slather/project.rb:239:in `profdata_coverage_dir': No coverage directory found. (StandardError)
```

**Comment by keisukeYamagishi** [comment]
I guess it's because the build_directory of Xcode 12.5 is as follows.

```
/var/root/Library/Developer/Xcode/DerivedData/sevens-bxrhnbgnthycnnbvajayyoaushxr/Build/Intermediates.noindex
```

So I try  "Preferences" -> "Locations" to change the Derived Data to the desired location🎉

<img width="825" alt="Screen Shot 2021-06-02 at 21 14 56" src="https://user-images.githubusercontent.com/5553852/120478282-a6e7c180-c3e7-11eb-8c9d-5a4bb45161b9.png">

I solve it🎉

**Comment by Arunperfutil** [comment]
After changing the build_directory in Xcode as above, still facing this error. is any other solution around for this? Thanks in advance.

**Comment by ebubekirsezer** [comment]
@Arunperfutil did you find any solution?

**Comment by keisukeYamagishi** [comment]
Hi👋  @Arunperfutil 
What kind of error is it?
Can you paste the output error here?

**Comment by keisukeYamagishi** [comment]
@ebubekirsezer 
Good sounds🤩
I confirmed  it
