### ISSUE TITLE
Slather coverage error while run

### ISSUE THREAD

**Issue by sshikalgar** [SlatherOrg/slather#510]
To verify you're ready to generate test coverage, run your test suite on your project, and then run:
`slather coverage -s --scheme Test-Demo ./Test-Demo.xcodeproj`

but after run above line I get following error:

```

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

**Comment by classclass2** [comment]
me too

**Comment by classclass2** [comment]
```
slather coverage -s --scheme SonarDemo --workspace SonarDemo.xcworkspace SonarDemo.xcodeproj
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/local/lib/nokogiri.bundle' (no such file), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/local/lib/nokogiri.bundle' (no such file), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/coverage_service/cobertura_xml_output.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'

```

**Comment by arinjay** [comment]
getting the same error.
Stuck on this

**Comment by MohammedBadr20s** [comment]
same error here too using Xcode 13.2.1

**Comment by kabirkhaan** [comment]
Following is the main reason `nokogiri-1.13.3-arm64-darwin` for error. 
Ruby `2.6.0` is way too old and it's a default version in mac.

- Please install rbenv
- Install and set the new version of ruby global by `rbenv global 3.1.2`. 
- Please make sure that ruby version  3.1.2
- run  `gem install bundle`

**Comment by sshikalgar** [comment]
`rbenv install -l`

> 2.6.9
> 2.7.5
> 3.0.3
> 3.1.1
> jruby-9.3.4.0
> mruby-3.0.0
> rbx-5.0
> truffleruby-22.0.0.2
> truffleruby+graalvm-22.0.0.2
> 
> Only latest stable releases for each Ruby implementation are shown.
> Use 'rbenv install --list-all / -L' to show all local versions.


After installing `ruby 3.1.1` and then later following `gem install bundle` still getting same issue with `ruby 2.6.0`

`ruby -v`

> ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
