### ISSUE TITLE
Slather failing with Xcode 16 beta 4

### ISSUE THREAD

**Issue by OliverBrown-Next** [SlatherOrg/slather#567]
With Xcode 16 beta 4 and Xcode 16 beta 5 I get the following error:

```sh
/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/json/common.rb:219:in `parse': unexpected token at '' (JSON::ParserError)
	from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/json/common.rb:219:in `parse'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:135:in `pathnames_per_binary'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:124:in `block in profdata_coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:123:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:123:in `profdata_coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:98:in `coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/command/coverage_command.rb:108:in `post'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/command/coverage_command.rb:64:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/bin/slather:17:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/slather:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/slather:25:in `<main>'
```

I assume the format has changed. I'm not sure how to find the source coverage file that is causing the problem.

**Comment by ksuther** [comment]
Xcode 16 beta creates a `.debug.dylib` binary next to the usual binary file and the original binary file is a stub that references the `.debug.dylib` file. See https://developer.apple.com/documentation/xcode/build-settings-reference#Enable-Debug-Dylib-Support.

Setting `ENABLE_DEBUG_DYLIB=NO` when building serves as a workaround on my end. I'm going to try making Slather look for `.debug.dylib` files by default.

**Comment by jarrodlombardo-EventBase** [comment]
If you have a scheme with 0% coverage, you get the same error output, even in XCode 15.
