### ISSUE TITLE
No scheme named 'MyScheme' found (Xcode 15.4)

### ISSUE THREAD

**Issue by mateomisas** [SlatherOrg/slather#569]
Hi, we are currently trying to generate reports with Slather using macOS 14 and Xcode 15.4. We added ruby and installed slather. This is our yml in our root directory:

```
coverage_service: gutter_json
xcodeproj: ./MyProject.xcodeproj
scheme: MyScheme
build_directory: ./Build
configuration: TestDebug
workspace: ./MyWorkspace.xcworkspace
verbose: true
output_directory: slather-report
ignore:
  - Pods/*
  - Carthage/*
 ```

We then execute the command `slather coverage` in our CI. Also, we plan to upload the report to Codecov.
But when trying this, it gives us this error always:

> /Users/runner/hostedtoolcache/Ruby/3.0.7/arm64/lib/ruby/gems/3.0.0/gems/slather-2.8.3/lib/slather/project.rb:517:in `find_binary_files': No scheme named 'MyScheme' found in /Users/runner/work/ios-app/ios-app/MyProject.xcodeproj (StandardError)

I'm sure the scheme exists and its being shared, and I'm not sure what else to do. Thanks in advance.

**Comment by jarrodlombardo** [comment]
I don't know if they're causing this issue or not, but remove the `./` from the front of the filenames. The slather.yml doesn't need that.

**Comment by mateomisas** [comment]
> I don't know if they're causing this issue or not, but remove the `./` from the front of the filenames. The slather.yml doesn't need that.

Yeah I know, but thanks

**Comment by jarrodlombardo** [comment]
They might be messing up finding something. Not sure.
Is the `ios-app/ios-app` part of the path correct? The double folder name looks unusual, but I don't know your actual folder structure.

**Comment by grantespo** [comment]
I'm able to run reports locally, but getting a similar issue in CI

> Slathering...
> No scheme named 'MY_SCHEME' found in /Users/distiller/project/MY_SCHEME.xcodeproj
> 
> Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
>         Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
>         If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
>         If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)
> 
> bundler: failed to load command: slather (/Users/distiller/.rbenv/versions/3.0.6/bin/slather)
> /Users/distiller/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/slather-2.8.3/lib/slather/project.rb:517:in `find_binary_files': No scheme named 'MY_SCHEME' found in /Users/distiller/project/MY_SCHEME.xcodeproj (StandardError)

**Comment by grantespo** [comment]
For me, I was able to build/test and run slather locally. But I was running into the error in CircleCi.

I had to remove these from my gitignore and re-commit:

*.xcodeproj/xcshareddata/
*.xcuserdatad/
*.xcuserdata/
