### ISSUE TITLE
Xcode 16.1 beta (and Slather 2.8.4) - Failed to load coverage: unsupported instrumentation profile format version

### ISSUE THREAD

**Issue by OliverBrown-Next** [SlatherOrg/slather#571]
I recently updated to Slather 2.8.4 to fix the Xcode 16 compatibility issue.

Using Xcode 16.1 beta, It works well locally, so thank you for that :) 
But when running in CI (Azure DevOps), I get the following error

```
Slathering...
error: Failed to load coverage: '/Users/runner/Library/Developer/Xcode/DerivedData/Assets-cecsqcpehsibqugchwzmtqbbxlil/Build/ProfileData/21543275-1377-4AC5-82B2-8929738D1C83/Coverage.profdata': unsupported instrumentation profile format version
error: Could not load coverage information
Slathered
```

I've attached the `Coverage.profdata` file, but I'm not sure what else I can do to investigate the issue. If there is anything else I can provide to help, please let me know.

[Coverage.profdata.zip](https://github.com/user-attachments/files/16906854/Coverage.profdata.zip)

One possible reason is the Azure DevOps build agent is an Intel mac and I'm running on Apple Silicon locally. This previously worked fine with Xcode 15.

**Comment by jarrodlombardo-EventBase** [comment]
My understanding was that XCode 15.0+ doesn't fully support Intel macs, so if this only repros on an Intel Mac with XCode 16+, my suggestions is to won't fix this. If we can get a repro on an Apple Silicon mac, we should investigate.

**Comment by VigneshPalanisamy** [comment]
is any workaround to solve this?

**Comment by SurendraMetrobank** [comment]
I'm also facing exactly same issue which @OliverBrown-Next is facing, my pipeline is Azure DevOps, Xcode 16.2 and Slather 2.8.4 
error: Failed to load coverage: '/Users/runner/work/1/s/mobile/ios/fastlane/build/Coverage/Coverage.profdata': unsupported instrumentation profile format version

**Comment by Cschau0701vip** [comment]
> My understanding was that XCode 15.0+ doesn't fully support Intel macs, so if this only repros on an Intel Mac with XCode 16+, my suggestions is to won't fix this. If we can get a repro on an Apple Silicon mac, we should investigate.

Hey @jarrodlombardo-EventBase, 

We're facing the same issue with the different combination tried on Azure DevOps server and local `XCode` on apple macOS.
Here are the below specifications:

> Local: -
- MacOS 15.3 / 15.4.1
- XCode 16.1 / 16.2 / 16.3
- iOS 18.0 / 18.2 / 18.4
- Slather 2.8.0 / 2.8.5

> Azure Agents: -
- MacOS 14.7.5 / 15.4.1
- XCode 16.1 / 16.2 / 16.3
- iOS 18.0 / 18.2 / 18.4
- Slather 2.8.0 / 2.8.5

Please find the below screenshots and error logs for the same:

- Server: 
  <img width="351" alt="Image" src="https://github.com/user-attachments/assets/643bdff7-c29e-4f08-b31d-1f73ac7c6428" />
  <img width="451" alt="Image" src="https://github.com/user-attachments/assets/afa4352c-6115-48fe-8156-12d96a7fc681" />

- Local: -
  <img width="724" alt="Image" src="https://github.com/user-attachments/assets/9fe8144e-cd44-4ebe-9f9b-d0c0a8295346" />
  <img width="894" alt="Image" src="https://github.com/user-attachments/assets/2c931e7e-81d4-4555-a235-f510d7d785f2" />
  <img width="194" alt="Image" src="https://github.com/user-attachments/assets/51b0ed21-f2fa-462f-b74e-b48107bc6739" />

- Error: -
  <img width="724" alt="Image" src="https://github.com/user-attachments/assets/7d560770-00e9-4405-93c9-126413ebbd49" />

```bash
error: Failed to load coverage: '/Users/runner/Library/Developer/Xcode/DerivedData/*/Build/ProfileData/337BCC5B-70E0-4F09-8553-44831B4857A7/Coverage.profdata': unsupported instrumentation profile format version
error: Could not load coverage information
/usr/local/Cellar/ruby@3.3/3.3.8/lib/ruby/3.3.0/json/common.rb:220:in `parse': unexpected token at '' (JSON::ParserError)
	from /usr/local/Cellar/ruby@3.3/3.3.8/lib/ruby/3.3.0/json/common.rb:220:in `parse'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/project.rb:135:in `pathnames_per_binary'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/project.rb:124:in `block in profdata_coverage_files'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/project.rb:123:in `each'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/project.rb:123:in `profdata_coverage_files'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/project.rb:98:in `coverage_files'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/command/coverage_command.rb:108:in `post'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/lib/slather/command/coverage_command.rb:64:in `execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/slather-2.8.0/bin/slather:17:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/slather:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/slather:25:in `<main>'
```

We have tried running multiple attempts and with different combinations but not able to get the `.profdata` generated. Could you please look into it and help us to resolve this issue?  Thank you!

**Comment by Cschau0701vip** [comment]
@jarrodlombardo-EventBase @weibel @OliverBrown-Next @SurendraMetrobank Any update on this issue?

**Comment by jarrodlombardo-EventBase** [comment]
@Cschau0701vip Your issue is a dup of https://github.com/SlatherOrg/slather/issues/567 and fixed in Slather 2.8.4. Your issue is not what the prior messages on this issue are talking about.

@SurendraMetrobank @OliverBrown-Next Please provide more information about your repro on a supported platform (XCode15+ requires an M-series Mac; intel hardware is no longer supported by XCode 15+ so Slather can't possibly work there)
