### ISSUE TITLE
slather coverage fails because of PBXGroup

### ISSUE THREAD

**Issue by trichard-jabra** [SlatherOrg/slather#573]
I have a floder in Xcode (16.1) that needs to remain a folder but I get this error.
Changing it to a group fixes the error but is not a solution

I am not using Cocoapods which is why I am reporting this here

```
Generating script.
Script contents:
slather coverage -x --output-directory /Users/vm1/jplus-agent/_work/1/coverage/
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/vm1/jplus-agent/_work/_temp/ffcfb277-30c5-41c2-844e-6228c9ec905e.sh
/Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid': `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"src", "sourceTree"=>"<group>"}` (RuntimeError)
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/project.rb:53:in `open'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:115:in `project'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:82:in `setup_output_directory'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:49:in `execute'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/bin/slather:17:in `<top (required)>'
	from /Users/vm1/.rbenv/versions/3.1.4/bin/slather:25:in `load'
	from /Users/vm1/.rbenv/versions/3.1.4/bin/slather:25:in `<main>'
/Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:268:in `new_from_plist': uninitialized constant Xcodeproj::Project::Object::PBXFileSystemSynchronizedRootGroup (NameError)


        klass = Object.const_get(attributes['isa'])
                      ^^^^^^^^^^
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/project.rb:53:in `open'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:115:in `project'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:82:in `setup_output_directory'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/lib/slather/command/coverage_command.rb:49:in `execute'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /Users/vm1/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/slather-2.8.4/bin/slather:17:in `<top (required)>'
	from /Users/vm1/.rbenv/versions/3.1.4/bin/slather:25:in `load'
	from /Users/vm1/.rbenv/versions/3.1.4/bin/slather:25:in `<main>'
Slathering...



```

**Comment by authiatr** [comment]
Hello, 

Slather uses the [Cocoapods/XcodeProj](https://github.com/CocoaPods/Xcodeproj) open-source library as a sub-dependency. 
Until last week [release](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0), XcodeProj didn't support Xcode 16 new attributes. 

Now, we need Slather's maintainers to update this library and release a new version.

**Comment by authiatr** [comment]
I opened a pull request #574. 
Hopefully, it will be approved and merged soon. 

Cheers
