### ISSUE TITLE
Friendly error messages

### ISSUE THREAD

**Issue by kylef** [SlatherOrg/slather#8]
The error handling could be changed so this doesn't output a Ruby backtrace to the user.

```bash
$ slather coverage -s CGFloatTypeTests/CGFloatType.xcodeproj
/Users/kylef/gems/gems/slather-1.0.1/lib/slather/project.rb:34:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)
	from /Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/simple_output.rb:13:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:50:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:30:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp.rb:6:in `Clamp'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:6:in `<top (required)>'
	from /Users/kylef/gems/bin/slather:23:in `load'
	from /Users/kylef/gems/bin/slather:23:in `<main>'
```

```bash
$ slather
Slathering...
/Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/coveralls.rb:24:in `coveralls_coverage_data': Environment variable `TRAVIS_JOB_ID` not set. Is this running on a travis build? (StandardError)
	from /Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/coveralls.rb:35:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:50:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:30:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp.rb:6:in `Clamp'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:6:in `<top (required)>'
	from /Users/kylef/gems/bin/slather:23:in `load'
	from /Users/kylef/gems/bin/slather:23:in `<main>'
```

**Comment by perfectpapa** [comment]
the same error
